# Generated by Django 3.1.4 on 2021-03-24 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=12)),
                ('proof_of_user', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bike_color', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue')], max_length=20)),
                ('bike_quantity', models.PositiveIntegerField()),
                ('bike_type', models.CharField(choices=[('Regular', 'Regular'), ('Non Gear', 'Non Gear'), ('Sports', 'Sports')], max_length=20)),
                ('bike_model', models.CharField(max_length=30)),
                ('bike_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
