# Generated by Django 3.1.4 on 2021-04-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_rent',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
