# Generated by Django 3.1.7 on 2021-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProof',
            fields=[
                ('Adhar_card', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('driving_licence', models.CharField(max_length=12)),
                ('passport_No', models.CharField(max_length=12)),
            ],
        ),
    ]
