# Generated by Django 3.1.4 on 2021-06-24 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBRS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bill_amount',
            new_name='Payment_bill_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Payment_Des',
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_bike_brand',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_bike_color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_bike_model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_bike_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_bike_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_emp_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_rent_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_rent_type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_station',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='userKey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_user',
            field=models.CharField(max_length=20),
        ),
    ]
