# Generated by Django 3.1.4 on 2021-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='bike_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
