# Generated by Django 3.1.4 on 2021-04-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0002_auto_20210416_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_superkey',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
