# Generated by Django 3.1.4 on 2021-03-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0002_station_bike_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_available',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
