# Generated by Django 3.1.4 on 2021-06-28 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0002_userproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
