# Generated by Django 3.1.4 on 2021-03-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBRS', '0002_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_adress', models.CharField(max_length=50)),
                ('station_phoneNo', models.CharField(max_length=10)),
                ('bikeQuantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_view',
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_brand',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='bike_rent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appBRS.bike'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Transection_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_amount', models.PositiveIntegerField()),
                ('Payment_Des', models.CharField(max_length=100)),
                ('Payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_phonNo', models.CharField(max_length=10)),
                ('station_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBRS.station')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBRS.station'),
            preserve_default=False,
        ),
    ]
