# Generated by Django 3.1.4 on 2021-06-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0003_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_emp_name',
            field=models.CharField(blank=True, default='Employee Name', max_length=30),
        ),
    ]
