# Generated by Django 3.1.4 on 2021-03-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0003_auto_20210325_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Transection_id',
            new_name='Transaction_id',
        ),
    ]
