# Generated by Django 3.1.4 on 2021-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0003_employee_employee_superkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
