# Generated by Django 3.1.4 on 2021-03-24 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rent', models.PositiveIntegerField()),
                ('daily_rent', models.PositiveIntegerField()),
                ('weekly_rent', models.PositiveIntegerField()),
                ('hourly_penalty', models.PositiveIntegerField()),
                ('daily_penalty', models.PositiveIntegerField()),
                ('weekly_penalty', models.PositiveIntegerField()),
                ('bike_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBRS.bike')),
            ],
        ),
    ]
